USE QLDT
GO

----CHO BIET NHUNG GIAO VIEN CO CUNG HO TEN, GIOI TINH, KHAC BM
----TQ
--SELECT GV.*
--FROM GIAOVIEN GV
--WHERE EXISTS (SELECT GVHT.HOTEN
--				FROM GIAOVIEN GVHT
--				WHERE GV.MABM = GVHT.MABM AND GV.MAGV!=GVHT.MAGV
--				AND GV.PHAI=GVHT.PHAI AND GV.MABM=GVHT.MABM)
--3
SELECT GV.*
FROM GIAOVIEN GV
JOIN DETAI DT
ON DT.GVCNDT=GV.MAGV
WHERE NOT EXISTS (SELECT *
				FROM THAMGIADT TGDT
				WHERE TGDT.MAGV=GV.MAGV)
--6
SELECT DISTINCT GV.*
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT
ON TGDT.MAGV=GV.MAGV
WHERE TGDT.MADT IN (SELECT TGDT1.MADT
				FROM THAMGIADT TGDT1
				JOIN GIAOVIEN AN
				ON AN.MAGV=TGDT1.MAGV
				WHERE AN.HOTEN=N'Nguyễn Hoài An') AND GV.HOTEN LIKE N'Nguyễn%'
