USE QLDT
GO
SELECT *
FROM GIAOVIEN GVDT
WHERE GVDT.MAGV IN(
SELECT GVDT1.MAGV
FROM GIAOVIEN GVDT1, GIAOVIEN GVBM1
WHERE GVDT1.MABM = GVBM1.MABM AND GVDT1.MAGV IN (
				SELECT GVCN1.MAGV
				FROM GIAOVIEN GVCN1
				JOIN DETAI DT1
				ON GVCN1.MAGV = DT1.GVCNDT
				GROUP BY GVCN1.MAGV
				HAVING COUNT(DT1.MADT)>= ALL (SELECT (COUNT(DT3.MADT))
											FROM GIAOVIEN GV3, DETAI DT3
											WHERE GV3.MAGV = DT3.GVCNDT
											GROUP BY GV3.MAGV)
				)
GROUP BY GVDT1.MAGV
HAVING COUNT(GVBM1.MAGV)>=2
)