USE QLDT
GO


SELECT * FROM GIAOVIEN
--Q35--
SELECT DISTINCT (GV.LUONG) LUONGCAONHAT
FROM GIAOVIEN GV
WHERE GV.LUONG >=ALL (SELECT GV.LUONG
				FROM GIAOVIEN GV)

--Q36--
SELECT *
FROM GIAOVIEN GV
WHERE GV.LUONG >=ALL (SELECT GV.LUONG
				FROM GIAOVIEN GV)

--Q37--
SELECT DISTINCT (GV.LUONG) LUONGCAONHATMONHTTT
FROM GIAOVIEN GV
WHERE GV.LUONG >=ALL (SELECT GV.LUONG
				FROM GIAOVIEN GV
				WHERE GV.MABM = 'HTTT')
AND GV.MABM = 'HTTT'

--Q38--
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
WHERE DATEDIFF(YEAR, GV.NGSINH, GETDATE()) >= ALL (SELECT DATEDIFF(YEAR, GV.NGSINH, GETDATE())
													FROM GIAOVIEN GV
													JOIN BOMON BM
													ON GV.MABM = BM.MABM
													WHERE BM.TENBM = N'Hệ thống thông tin')
AND BM.TENBM = N'Hệ thống thông tin'

--Q39--
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
JOIN KHOA K
ON BM.MAKHOA = K.MAKHOA
WHERE DATEDIFF(YEAR, GV.NGSINH, GETDATE()) <= ALL (SELECT DATEDIFF(YEAR, GV.NGSINH, GETDATE())
													FROM GIAOVIEN GV
													JOIN BOMON BM
													ON GV.MABM = BM.MABM
													JOIN KHOA K
													ON BM.MAKHOA = K.MAKHOA
													WHERE K.TENKHOA = N'Công nghệ thông tin')
AND K.TENKHOA = N'Công nghệ thông tin'

--Q40--
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
JOIN KHOA K
ON BM.MAKHOA = K.MAKHOA
WHERE GV.LUONG >= ALL (SELECT GV.LUONG
						FROM GIAOVIEN GV)

--Q41--
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG IN(SELECT MAX(GV2.LUONG)
					FROM GIAOVIEN GV2
					GROUP BY GV2.MABM
					HAVING GV.MABM = GV2.MABM)

--Q42--
SELECT DT.TENDT
FROM DETAI DT
WHERE DT.MADT NOT IN (SELECT TGDT.MADT
						FROM THAMGIADT TGDT
						JOIN GIAOVIEN GV
						ON GV.MAGV = TGDT.MAGV
						WHERE GV.HOTEN = N'Nguyễn Hoài An')

--Q43--
SELECT DT.TENDT, (GV.HOTEN) GVCNDT
FROM DETAI DT
JOIN GIAOVIEN GV
ON GV.MAGV = DT.GVCNDT
WHERE DT.MADT NOT IN (SELECT TGDT.MADT
						FROM THAMGIADT TGDT
						JOIN GIAOVIEN GV
						ON GV.MAGV = TGDT.MAGV
						WHERE GV.HOTEN = N'Nguyễn Hoài An')

--Q44--
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
JOIN KHOA K
ON K.MAKHOA = BM.MAKHOA
WHERE GV.MAGV NOT IN (SELECT TGDT.MAGV
						FROM THAMGIADT TGDT)
AND K.TENKHOA = N'Công nghệ thông tin'

--Q45--
SELECT *
FROM GIAOVIEN GV
WHERE GV.MAGV NOT IN (SELECT TGDT.MAGV
						FROM THAMGIADT TGDT)

--Q46--
SELECT *
FROM GIAOVIEN GV
WHERE GV.LUONG > (SELECT AN.LUONG
					FROM GIAOVIEN AN
					WHERE AN.HOTEN = N'Nguyễn Hoài An')

--Q47--
SELECT TBM.*
FROM BOMON BM
JOIN GIAOVIEN TBM
ON BM.TRUONGBM = TBM.MAGV
WHERE TBM.MAGV IN (SELECT GV.MAGV
				FROM GIAOVIEN GV
				JOIN THAMGIADT TGDT
				ON GV.MAGV = TGDT.MAGV
				GROUP BY GV.MAGV
				HAVING COUNT(TGDT.MADT)>= 1)

--Q48--
 SELECT *
 FROM GIAOVIEN GV1, GIAOVIEN GV2
 WHERE GV1.HOTEN LIKE GV2.HOTEN AND GV2.PHAI = GV1.PHAI  AND GV1.MAGV != GV2.MAGV AND GV1.MABM = GV2.MABM

--Q49--
SELECT *
FROM GIAOVIEN GV
WHERE GV.LUONG >= (SELECT MIN(GV.LUONG)
					FROM GIAOVIEN GV
					JOIN BOMON BM
					ON GV.MABM = BM.MABM
					WHERE BM.TENBM = N'Công nghệ phần mềm')

--Q50--
SELECT *
FROM GIAOVIEN GV
WHERE GV.LUONG > (SELECT MAX(GV.LUONG)
					FROM GIAOVIEN GV
					JOIN BOMON BM
					ON GV.MABM = BM.MABM
					WHERE BM.MABM = N'Hệ thống thông tin')

--Q51--
SELECT K.TENKHOA
FROM KHOA K
JOIN BOMON BM
ON BM.MAKHOA = K.MAKHOA
JOIN GIAOVIEN GV
ON GV.MABM = BM.MABM
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(GV.MAGV) = (SELECT MAX(SOLUONGGIAOVIEN) 
FROM (SELECT (K.MAKHOA) MK, COUNT(GV.MAGV) SOLUONGGIAOVIEN
FROM KHOA K
JOIN BOMON BM
ON K.MAKHOA = BM.MAKHOA
JOIN GIAOVIEN GV
ON BM.MABM = GV.MABM
GROUP BY K.MAKHOA) AS T)

--Q52--
SELECT *
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT DT.GVCNDT
	FROM DETAI DT
	GROUP BY DT.GVCNDT
	HAVING COUNT(DT.MADT) = (
		SELECT MAX(SOLUONGDT)
		FROM (
			SELECT DT.GVCNDT, COUNT(DT.MADT) SOLUONGDT
			FROM DETAI DT
			GROUP BY DT.GVCNDT
		) AS T
	)
)

--Q53--
SELECT BM.MABM
FROM BOMON BM
JOIN GIAOVIEN GV
ON BM.MABM = GV.MABM
GROUP BY BM.MABM
HAVING COUNT(GV.MAGV) = (
	SELECT MAX(SLGV)
	FROM (
		SELECT COUNT(GV.MAGV) SLGV
		FROM BOMON BM
		JOIN GIAOVIEN GV
		ON BM.MABM = GV.MABM
		GROUP BY BM.MABM
	) AS T
)

--Q54--
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
WHERE GV.MAGV IN (
	SELECT TGDT.MAGV
	FROM THAMGIADT TGDT
	GROUP BY TGDT.MAGV
	HAVING COUNT(TGDT.MADT) = (
		SELECT MAX(SOLUONGDT)
		FROM (
			SELECT COUNT(TGDT.MADT) SOLUONGDT
			FROM THAMGIADT TGDT
			GROUP BY TGDT.MAGV
		) AS T
	)
)

--Q55--
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
WHERE GV.MAGV IN (
	SELECT TGDT.MAGV
	FROM THAMGIADT TGDT
	GROUP BY TGDT.MAGV
	HAVING COUNT(TGDT.MADT) = (
		SELECT MAX(SOLUONGDT)
		FROM (
			SELECT COUNT(TGDT.MADT) SOLUONGDT
			FROM THAMGIADT TGDT
			GROUP BY TGDT.MAGV
		) AS T
	)
) AND BM.TENBM = N'Hệ thống thông tin'

--Q56--
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM
ON GV.MABM = BM.MABM
WHERE GV.MAGV IN (
	SELECT NT.MAGV
	FROM NGUOITHAN NT
	GROUP BY NT.MAGV
	HAVING COUNT(NT.TEN) = (
		SELECT MAX(SLNT)
		FROM (
			SELECT COUNT(NT.TEN) SLNT
			FROM NGUOITHAN NT
			GROUP BY NT.MAGV
		) AS T
	)
)

--Q57--
SELECT GV.HOTEN
FROM BOMON BM
JOIN GIAOVIEN GV
ON GV.MAGV = BM.TRUONGBM
WHERE BM.TRUONGBM IN (
	SELECT DT.GVCNDT
	FROM DETAI DT
	GROUP BY DT.GVCNDT
	HAVING COUNT(DT.MADT) = (
		SELECT MAX(SOLUONGDT)
		FROM (
			SELECT DT.GVCNDT, COUNT(DT.MADT) SOLUONGDT
			FROM DETAI DT
			GROUP BY DT.GVCNDT
		) AS T
	)
)