USE QLDT
GO

--ÔN TH?C HÀNH CU?I KÌ--
--Q1--
SELECT BM2.*
FROM BOMON BM2
WHERE BM2.MABM IN(
SELECT BM.MABM
FROM BOMON BM
JOIN GIAOVIEN GV
ON BM.MABM = GV.MABM
JOIN GV_DT DT
ON GV.MAGV = DT.MAGV
GROUP BY BM.MABM
HAVING COUNT(DISTINCT GV.MAGV) =(
SELECT MAX(SLGVCOSDT)
FROM (SELECT (BM1.MABM) MABM, (COUNT(DISTINCT GV.MAGV)) SLGVCOSDT
FROM BOMON BM1
JOIN GIAOVIEN GV
ON BM1.MABM = GV.MABM
JOIN GV_DT DT
ON GV.MAGV = DT.MAGV
GROUP BY BM1.MABM) AS T))

--Q2--
SELECT *
FROM GIAOVIEN
WHERE MAGV IN (
SELECT GV.MAGV
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT IN
(SELECT DT.MADT
FROM DETAI DT
JOIN GIAOVIEN SON
ON DT.GVCNDT = SON.MAGV
WHERE SON.HOTEN = N'Trương Nam Sơn')
GROUP BY GV.MAGV
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT COUNT(DISTINCT DT1.MADT)
FROM DETAI DT1
JOIN GIAOVIEN SON1
ON DT1.GVCNDT = SON1.MAGV
WHERE SON1.HOTEN = N'Trương Nam Sơn'))

--Q3--
SELECT *
FROM GIAOVIEN GV
WHERE MAGV IN(
SELECT GV.MAGV
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT IN (SELECT DT.MADT
					FROM DETAI DT
					WHERE DT.KINHPHI > 80)
GROUP BY GV.MAGV
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT COUNT(DISTINCT DT1.MADT)
					FROM DETAI DT1
					WHERE DT1.KINHPHI > 80))

--Q4--
GO
DROP PROCEDURE spHienThi_DSGV_ThamGia_DeTai
GO
CREATE PROCEDURE spHienThi_DSGV_ThamGia_DeTai @tuNgay DATE, @denNgay DATE
AS
BEGIN
	DECLARE @soNgayNhap int
	IF(@tuNgay > @denNgay) 
	BEGIN
		PRINT N'Loi nhap ngay'
		RETURN
	END
	ELSE
	BEGIN
	DECLARE @vtable TABLE(MaDT char(3))
	DECLARE @count int, @MaDT char(3), @ngayBD DATE, @ngayKT DATE, @countSoDT int

	DECLARE @deTaiThoaYC TABLE(MADT char(3))
	INSERT INTO @vtable
		SELECT MADT
		FROM DETAI

	SELECT @count = COUNT(*)
	FROM @vtable

	WHILE(@count > 0)
	BEGIN
		SELECT TOP 1 @MaDT = DT.MADT, @ngayBD = DT.NGAYBD, @ngayKT = DT.NGAYKT
		FROM @vtable VT, DETAI DT
		WHERE VT.MaDT = DT.MADT

		IF(@tuNgay < @ngayBD AND @denNgay < @ngayKT)
		BEGIN
			INSERT INTO @deTaiThoaYC
			SELECT MaDT
			FROM @vtable
			WHERE MaDT = @MaDT
		END
		DELETE @vtable WHERE MaDT = @MaDT;

		SET @count = @count -1
	END
		IF((SELECT COUNT(MADT) FROM @deTaiThoaYC) = 0)
		RETURN

		SET @countSoDT = (SELECT COUNT(MADT) FROM @deTaiThoaYC)
		--PRINT N'So luong de tai thoa yeu cau la: ' + @countSo
		PRINT @countSoDT

		SELECT DT.*, T.SLGV
		FROM 
		(SELECT DT.MADT, (COUNT(DISTINCT TGDT.MAGV)) SLGV
		FROM DETAI DT
		LEFT JOIN THAMGIADT TGDT
		ON DT.MADT = TGDT.MADT
		WHERE DT.MADT IN (SELECT MADT FROM @deTaiThoaYC)
		GROUP BY DT.MADT) AS T
		JOIN DETAI DT
		ON T.MADT = DT.MADT

		SELECT GVCN.*
		FROM DETAI DT
		LEFT JOIN GIAOVIEN GVCN
		ON DT.GVCNDT = GVCN.MAGV
		WHERE DT.MADT IN (SELECT MADT FROM @deTaiThoaYC)

		SELECT GVTG.*
		FROM DETAI DT
		LEFT JOIN THAMGIADT TGDT
		ON DT.MADT = TGDT.MADT
		JOIN GIAOVIEN GVTG
		ON TGDT.MAGV = GVTG.MAGV
		WHERE DT.MADT IN (SELECT MADT FROM @deTaiThoaYC)
		ORDER BY GVTG.NGSINH DESC
		END
END
GO

SET DATEFORMAT 'DMY'
Exec spHienThi_DSGV_ThamGia_DeTai '19/10/2007', '19/10/2009'