USE QLDT
GO

--Q75--
SELECT GV.HOTEN, (BM.TENBM) TRUONGBM
FROM GIAOVIEN GV
LEFT JOIN BOMON BM
ON GV.MAGV = BM.TRUONGBM

--Q76--
SELECT BM.TENBM, (GV.HOTEN) TENTRUONGBM
FROM BOMON BM
LEFT JOIN GIAOVIEN GV
ON BM.TRUONGBM = GV.MAGV

--Q77--
SELECT GV.HOTEN, (DT.TENDT) DETAICN
FROM GIAOVIEN GV
LEFT JOIN DETAI DT
ON GV.MAGV = DT.GVCNDT

--Q78--
SELECT GV.HOTEN, (CASE
				WHEN GV.LUONG < 1800 THEN N'THẤP'
				WHEN GV.LUONG >= 1800 AND GV.LUONG <= 2200 THEN N'TRUNG BÌNH'
				WHEN GV.LUONG > 2200 THEN N'CAO'
				END) LUONG
FROM GIAOVIEN GV

--Q79--
SELECT GV1.MAGV, GV1.HOTEN, (SELECT COUNT(*)
			FROM GIAOVIEN GV
			WHERE GV.LUONG >= GV1.LUONG) HANG
FROM GIAOVIEN GV1

--Q80--
SELECT GV.HOTEN, (CASE
				WHEN BM.MABM IS NOT NULL AND K.MAKHOA IS NULL THEN GV.LUONG + 300
				WHEN BM.MABM IS NULL AND K.MAKHOA IS NOT NULL THEN GV.LUONG + 600
				WHEN BM.MABM IS NOT NULL AND K.MAKHOA IS NOT NULL THEN GV.LUONG + 900		
				WHEN BM.MABM IS NULL AND K.MAKHOA IS NULL THEN GV.LUONG
				END) THUNHAP
FROM GIAOVIEN GV
LEFT JOIN BOMON BM
ON GV.MAGV = BM.TRUONGBM
LEFT JOIN KHOA K
ON GV.MAGV = K.TRUONGKHOA

--Q81--
SELECT GV.*, (CASE
		WHEN GV.PHAI = N'Nữ' THEN YEAR(GETDATE()) + (55 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		WHEN GV.PHAI = N'Nam' THEN YEAR(GETDATE()) + (65 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		END) NAMNGHIHUU
FROM GIAOVIEN GV

--Q82--
SELECT GV.MAGV, GV.HOTEN, (GVQL.HOTEN) HOTENGVQL
FROM GIAOVIEN GV
LEFT JOIN GIAOVIEN GVQL
ON GV.GVQLCM = GVQL.MAGV

--Q83--
SELECT BM.MABM, BM.TENBM, TBM.MAGV, TBM.HOTEN, (COUNT(DISTINCT DSGV.MAGV)) SOLUONGGV
FROM BOMON BM
LEFT JOIN GIAOVIEN TBM
ON BM.TRUONGBM = TBM.MAGV
LEFT JOIN GIAOVIEN DSGV
ON BM.MABM = DSGV.MABM
GROUP BY BM.MABM, BM.TENBM, TBM.MAGV, TBM.HOTEN

--Q84--
SELECT DISTINCT GV.*, CV.*
FROM GIAOVIEN GV
LEFT JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
LEFT JOIN CONGVIEC CV
ON TGDT.MADT = CV.MADT
WHERE GV.PHAI = 'Nam'

--Q85--
SELECT DISTINCT GV.*, CV.*
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT .MAGV
JOIN CONGVIEC CV
ON TGDT.MADT = CV.MADT
WHERE TGDT.MADT = '001'

--Q86--
SELECT GV.MAGV, GV.HOTEN, (CASE
		WHEN GV.PHAI = N'Nữ' THEN YEAR(GETDATE()) + (55 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		WHEN GV.PHAI = N'Nam' THEN YEAR(GETDATE()) + (65 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		END) NAMNGHIHUU
FROM GIAOVIEN GV
JOIN BOMON BM
ON BM.TRUONGBM = GV.MAGV
WHERE (CASE
		WHEN GV.PHAI = N'Nữ' THEN YEAR(GETDATE()) + (55 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		WHEN GV.PHAI = N'Nam' THEN YEAR(GETDATE()) + (65 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		END) = 2014

--Q87--
SELECT GV.MAGV, GV.HOTEN, (CASE
		WHEN GV.PHAI = N'Nữ' THEN YEAR(GETDATE()) + (55 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		WHEN GV.PHAI = N'Nam' THEN YEAR(GETDATE()) + (65 - DATEDIFF(YEAR, GV.NGSINH, GETDATE()))
		END) NAMNGHIHUU
FROM GIAOVIEN GV
JOIN KHOA K
ON K.TRUONGKHOA = GV.MAGV

--Q88--
CREATE TABLE DANHSACHTHIDUA
(
	MAGV CHAR(3),
	SODTDAT INT,
	DANHHIEU NVARCHAR(100)
)
GO
INSERT DANHSACHTHIDUA(MAGV,SODTDAT)
VALUES
	('001', 0),
	('002', 1),
	('003', 4),
	('004', 8)
GO
UPDATE DANHSACHTHIDUA SET DANHHIEU = (CASE
									WHEN SODTDAT = 0 THEN N'Chưa hoàn thành nhiệm vụ'
									WHEN SODTDAT >=1 AND SODTDAT <=2 THEN N'Hoàn thành nhiệm vụ'
									WHEN SODTDAT >=3 AND SODTDAT <=5 THEN N'iên tiến'
									WHEN SODTDAT >=6 THEN N'Lao động xuất sắc'
									END)