USE QLDT
GO

--1--
SELECT *
FROM BOMON BM
WHERE BM.MABM IN (
SELECT (BM.MABM) MABM
FROM BOMON BM
JOIN GIAOVIEN GV
ON BM.MABM = GV.MABM
JOIN GV_DT GVDT
ON GV.MAGV = GVDT.MAGV
GROUP BY BM.MABM
HAVING COUNT(GV.MAGV) = (
SELECT MAX(T.SLGV)
FROM (
SELECT (BM.MABM) MABM, COUNT(GV.MAGV) SLGV
FROM BOMON BM
JOIN GIAOVIEN GV
ON BM.MABM = GV.MABM
JOIN GV_DT GVDT
ON GV.MAGV = GVDT.MAGV
GROUP BY BM.MABM) AS T))

--DAPANCAU1--
SELECT BM.MABM, BM.TENBM, COUNT(DT.DIENTHOAI) as 'SLGV co DT'
FROM BOMON BM, GIAOVIEN GV, GV_DT DT
WHERE BM.MABM = GV.MABM AND GV.MAGV = DT.MAGV
GROUP BY BM.MABM, BM.TENBM
HAVING COUNT(DT.DIENTHOAI) >= ALL (
	SELECT COUNT(DT.DIENTHOAI)
	FROM BOMON BM, GIAOVIEN GV, GV_DT DT
	WHERE BM.MABM = GV.MABM AND GV.MAGV = DT.MAGV
	GROUP BY BM.MABM, BM.TENBM
	)
--2--
SELECT *
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
SELECT GV.MAGV
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT IN (SELECT DT.MADT
					FROM DETAI DT
					JOIN GIAOVIEN SON
					ON DT.GVCNDT = SON.MAGV
					WHERE SON.HOTEN = N'Trương Nam Sơn')
GROUP BY GV.MAGV
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT COUNT(DISTINCT DT.MADT)
					FROM DETAI DT
					JOIN GIAOVIEN SON
					ON DT.GVCNDT = SON.MAGV
					WHERE SON.HOTEN = N'Trương Nam Sơn'))

--DAPANCAU2--
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT MADT
	FROM DETAI DT, GIAOVIEN GV1
	WHERE DT.GVCNDT = GV1.MAGV AND GV1.HOTEN = N'Trương Nam Sơn'
EXCEPT
	SELECT MADT
	FROM THAMGIADT TG
	WHERE TG.MAGV = GV.MAGV
	)

--3--
SELECT *
FROM GIAOVIEN GV1
WHERE GV1.MAGV IN (
SELECT GV.MAGV
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT IN (SELECT DT.MADT
					FROM DETAI DT
					WHERE DT.KINHPHI > 80)
GROUP BY GV.MAGV
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT COUNT(DISTINCT TGDT1.MADT)
									FROM THAMGIADT TGDT1
									WHERE GV.MAGV = TGDT1.MAGV))

--DAPANCAU3--
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT GV.MAGV
	FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
	WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.KINHPHI > 80
	GROUP BY GV.MAGV
	HAVING COUNT(DISTINCT DT.MADT) = (
		SELECT COUNT(DISTINCT TG.MADT)
		FROM THAMGIADT TG
		WHERE GV.MAGV = TG.MAGV 
		)
	)

DROP PROCEDURE spHienThi_DSGV_ThamGia_DeTai
GO

CREATE PROCEDURE spHienThi_DSGV_ThamGia_DeTai @tuNgay DATE, @denNgay DATE
AS
BEGIN
	IF(@tuNgay > @denNgay)
	BEGIN
		PRINT N'Loi nhap ngay'
		RETURN
	END

	DECLARE @deTaiDungYC TABLE(MaDT CHAR(3))
	DECLARE @count INT, @MaDT CHAR(3)

	INSERT INTO @deTaiDungYC
		SELECT MADT
		FROM DETAI
		WHERE (NGAYBD >= @tuNgay AND NGAYKT <= @denNgay)
		ORDER BY NGAYBD DESC

	SELECT @count = (SELECT COUNT(*) FROM @deTaiDungYC)
	IF(@count = 0)
	BEGIN
		PRINT N'Khong co de tai thoa yeu cau'
		RETURN
	END

	DECLARE @i INT
	SET @i = 1
	WHILE(@i <= @count)
	BEGIN
		SELECT TOP 1 @MaDT = MaDT FROM @deTaiDungYC
		PRINT N'DETAI' + CAST(@i AS CHAR(3)) + '/' + CAST(@count AS CHAR(3))

		SELECT DT1.*, T.SLGV
		FROM (
		SELECT DT.MADT, COUNT(DISTINCT TGDT.MAGV) AS SLGV
		FROM DETAI DT
		JOIN THAMGIADT TGDT
		ON DT.MADT = TGDT.MADT
		WHERE DT.MADT = @MaDT
		GROUP BY DT.MADT) AS T
		JOIN DETAI DT1
		ON T.MADT = DT1.MADT

		SELECT GV.*
		FROM GIAOVIEN GV, DETAI DT
		WHERE DT.GVCNDT = GV.MAGV AND DT.MADT = @MaDT

		SELECT GV.*
		FROM THAMGIADT TGDT
		JOIN GIAOVIEN GV
		ON TGDT.MAGV = GV.MAGV
		WHERE TGDT.MADT = @MaDT
		ORDER BY GV.NGSINH

		SET @i = @i + 1
		DELETE @deTaiDungYC WHERE MaDT = @MaDT
	END
END

SET DATEFORMAT 'DMY'
EXEC spHienThi_DSGV_ThamGia_DeTai '1-1-2000', '1-1-2010'

DROP PROCEDURE spHienThi_DSGV_ThamGia_DeTai
GO

CREATE PROCEDURE spHienThi_DSGV_ThamGia_DeTai @Tu_Ngay date, @Den_Ngay date
AS
BEGIN
	IF (@Tu_Ngay > @Den_Ngay)
	BEGIN
		RAISERROR('Tham so vao ko hop le', 16, 1);
		RETURN;
	END

	DECLARE @DS_DETAI TABLE(MADT char(10), GVCNDT char(10));
	INSERT INTO @DS_DETAI
		SELECT MADT, GVCNDT
		FROM DETAI
		WHERE (@Tu_Ngay <= NGAYBD AND NGAYBD <= @Den_Ngay )
			OR (@Tu_Ngay <= NGAYKT AND NGAYKT <= @Den_Ngay )
		ORDER BY NGAYBD DESC;

	DECLARE @SL_DETAI int;
	SELECT @SL_DETAI = COUNT(*) FROM @DS_DETAI;
	PRINT 'So luong de tai thoa yeu cau:' + CAST(@SL_DETAI AS CHAR(10));
	IF ( @SL_DETAI = 0 ) RETURN;

	DECLARE @i int, @MADT char(10), @GVCNDT char(10), @SL_GVTG int;
	SET @i = 1;
	WHILE ( @i <= @SL_DETAI )
	BEGIN
		SELECT '== DE TAI #  ' + CAST(@i as char(3)) + ' / ' + CAST(@SL_DETAI as char(3)) + '======================================================================';
		SELECT TOP 1 @MADT = MADT, @GVCNDT = GVCNDT FROM @DS_DETAI;

		SET @SL_GVTG = (SELECT COUNT(DISTINCT MAGV)
			FROM THAMGIADT
			WHERE MADT = @MADT AND MAGV <> @GVCNDT)

		SELECT DT.*, @SL_GVTG as 'SLGV tham gia'
			FROM DETAI DT
			WHERE MADT = @MADT;

		SELECT GV.*
			FROM GIAOVIEN GV
			WHERE MAGV = @GVCNDT;

		IF ( @SL_GVTG > 0 )
			SELECT GV.*
			FROM GIAOVIEN GV
			WHERE GV.MAGV <> @GVCNDT AND
				GV.MAGV IN (SELECT DISTINCT TG.MAGV
							FROM THAMGIADT TG
							WHERE TG.MADT = @MADT )
			ORDER BY (YEAR(GETDATE()) - YEAR(GV.NGSINH)) DESC;

		SET @i = @i + 1;
		DELETE @DS_DETAI WHERE MADT = @MADT;
	END

END
GO