USE master
GO
IF DB_ID('QLTV') IS NOT NULL
	DROP DATABASE QLTV
GO
CREATE DATABASE QLTV
GO
USE QLTV
GO
CREATE TABLE DOI
(
	IDDoi CHAR(1),
	TenDoi NVARCHAR(40),
	DoiTruong CHAR(1)

	CONSTRAINT PK_DOI
	PRIMARY KEY (IDDoi)
)
CREATE TABLE BOTRI
(
	IDDOI CHAR(1),
	IDThanhVien CHAR(1),
	DiaChi NVARCHAR(50),
	NhiemVu NVARCHAR(50),
	QuanLi CHAR(1)

	CONSTRAINT PK_BOTRI
	PRIMARY KEY(IDDOI,IDThanhVien)
)

CREATE TABLE THANHVIEN
(
	IDThanhVien CHAR(1),
	HoTen NVARCHAR(40),
	SoCMND CHAR(9),
	DiaChi NVARCHAR(50),
	NgaySinh DATE

	CONSTRAINT PK_THANHVIEN
	PRIMARY KEY(IDThanhVien)
)
GO
ALTER TABLE DOI
ADD
	CONSTRAINT FK_DOI_THANHVIEN
	FOREIGN KEY(DoiTruong)
	REFERENCES THANHVIEN
ALTER TABLE BOTRI
ADD
	CONSTRAINT FK_BOTRI_DOI
	FOREIGN KEY(IDDOI)
	REFERENCES DOI,
	CONSTRAINT FK_BOTRI_THANHVIEN
	FOREIGN KEY(IDThanhVien)
	REFERENCES THANHVIEN,
	CONSTRAINT FK_BOTRI_QUANLI
	FOREIGN KEY(QuanLi)
	REFERENCES THANHVIEN
SET DATEFORMAT 'DMY'
INSERT THANHVIEN(IDThanhVien,HoTen,SoCMND,DiaChi,NgaySinh)
VALUES
	('1',N'Nguyễn Quan Tùng', '240674018', 'TPHCM', '30/1/2000'),
	('2', N'Lưu Phi Nam', '240674027', N'Quảng Nam', '12/3/2001' )
INSERT DOI(IDDoi,TenDoi,DoiTruong)
VALUES
	('2', N'Đôi Tân Phú', '1')
INSERT BOTRI(IDDOI,IDThanhVien,DiaChi,NhiemVu,QuanLi)
VALUES
	('2', '2', N'123 Vườn Lài Tân Phú', N'Trực khu vực vòng xoay 1', '1')
SELECT D.TenDoi,T.HoTen
FROM DOI D
JOIN BOTRI B
ON D.IDDoi=B.IDDOI
JOIN THANHVIEN T
ON D.DoiTruong=T.IDThanhVien
WHERE CHARINDEX(N'Tân Phú', B.DiaChi) != 0

SELECT TENQL.HoTen TenQuanLi, COUNT(T.IDThanhVien) SOLUONGTHANHVIEN
FROM BOTRI B
JOIN THANHVIEN T
ON B.IDThanhVien=T.IDThanhVien
JOIN THANHVIEN TENQL
ON B.QuanLi=TENQL.IDThanhVien
WHERE T.NgaySinh IS NOT NULL
GROUP BY B.QuanLi, TENQL.HoTen